---
title: "01_01_country_merge.Rmd"
author: "Vinay K L"
date: "2023-10-12"
output: pdf_document
---

```{r loading libraries, include=FALSE}
library(tidyverse)
library(dplyr)
library(lubridate)
library(countrycode)
library(stringr)
library(fuzzyjoin)
library(readr)
```

```{r}
#lets keep the cleaned_df separately and work on the new dataframe to keep things in control
country_clean <- cleaned_df
```

```{r, country count check}
# to cound the unique entries
country_counts_check <- country_clean %>%
  group_by(country) %>%
  summarise(count = n())
# 1331 entries - T 
```

```{r, merging countries}
# Creating a list of all the 'country functions' to store the names and then looping over the column to replace the entries. 

# There's always gonna be a descripency on the total number of countries. I am following www.countrycode.org to keep things in check which has an ISO 3166-1 alpha-3 (https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) these includes Oceania and Island countries.

replace_functions <- list (
# United States of America
    USA <- function(x) {
  if (grepl("United  States|	
United  States  Of  America|United  States  Minor  Outlying  Islands|Usa|The  United  States  Midway  Atoll ( Usa)| Alaska| American  Samoa| Baker  Island| Arctic  America| Commonwealth  Of  The  Northern  Mariana  Islands| Dmns  Grounds, 2001  Colorado  Blvd,  West  Atrium  Sidewalk", x, ignore.case = TRUE)) {
    return("The United States of America")
  } else {
    return(x)
  }
},
# Philipines
  PHL <- function(x) {
  if (grepl("Philippine| Philippine  Ids| Philippine  Islands| Philippine  Isls| Philippine's|Philippines| Philippines  Isl| Philippines  Islands|Phill| Phillipine  Islands| Phillipines| Philip| Batan  Island| Batanta  Islands| Bongao  Islands", x, ignore.case = TRUE)) {
    return("Philippines")
  } else {
    return(x)
  }
},
# Seychelles
  SYC <- function(x) {
  if (grepl("Aldabra  Islands|Aldabrar  Islands| Sychelles  Islands", x, ignore.case = TRUE)) {
    return("Seychelles")
  } else {
    return(x)
  }
},
#Antigua and Barbuda
  ATG <- function(x) {
  if (grepl("Antigua| Antigua  And  Barbuda", x, ignore.case = TRUE)) {
    return(" Antigua  And  Barbuda")
  } else {
    return(x)
  }
},
# Portugal
  PRT <- function(x) {
  if (grepl(" Azores  Archipelago;  Portugal| Madeira;  Portugal| Portugal| Azores", x, ignore.case = TRUE)) {
    return("Portugal")
  } else {
    return(x)
  }
},
#Bahamas
  BHS <- function(x) {
  if (grepl(" Bahama  Islands|Bahamas| Bahamas,  The", x, ignore.case = TRUE)) {
    return("Bahamas")
  } else {
    return(x)
  }
},
# Bhutan
  BTN <- function(x) {
  if (grepl("Bhutan| Bhutan,  India", x, ignore.case = TRUE)) {
    return("Bhutan")
  } else {
    return(x)
  }
},
#Bosnia  And  Hercegovina
  BIH <- function(x) {
  if (grepl(" Bosnia  And  Hercegovina| Bosnia  And  Herzegovina", x, ignore.case = TRUE)) {
    return("Bosnia  And  Herzegovina")
  } else {
    return(x)
  }
},
# British Overseas Territories
  IOT <- function(x) {
  if (grepl(" Anguilla| Ascension  Island| Saint  Helena,  Ascension  And  Tristan  Da  Cunha| Bermuda| British  Virgin  Islands| Cayman  Islands| Grand  Cayman| Grand  Cayman  Islands| Falkland  Islands| Falkland  Islands ( Malvinas)| Falkland  Islands;  British  Overseas  Territories| Gilbert  Islands| Montserrat| Gough  Island;  St  Helena  Dependency,  Tristan  Da  Cunha  Island  Group;  British  Overseas  Territory| Saint  Helena| Saint  Helena,  Ascension  And  Tristan  Da  Cunha| St.  Helena| Tristan  Da  Cunha| Turks  And  Caicos  Islands| Caicos| Caicos  Islands", x, ignore.case = TRUE)) {
    return("British Overseas Territories")
  } else {
    return(x)
  }
},
# Spain
  ESP <- function(x) {
  if (grepl(" Canary  Islands| Canary  Islands;  Spain| Spain", x, ignore.case = TRUE)) {
    return("Spain")
  } else {
    return(x)
  }
},
#Indonesia
  IDN <- function(x) {
  if (grepl(" C.  Celebes|Celebes| Celebes  Islands| Celebres| Cent.  Celebes| Centr.  Celebes| Djampea  Islands. ( S.  Of  Celebes)| E  Celebes| E  Of  Celebes| E.  Celebes| E.  Celebes  Islands| E.  Of  Celebes| E.  Of  Celebes  Islands| E.of  Celebes| East  Celebes| East  Of  Celebes| N  Celebes| N.  Celebes| N.  Celebes  Islands| N.  E.of  Celebes| N.  Of  Celebes| N.celebes| N.e.  Celebes| N.of  Celebes| N.w.  Celebes| North  Celebes| Nw.  Celebes| S  Celebes| S.  Celebes| S.  Celebes  Islands| S.  Central  Celebes| S.  Of  Celebes| S.e.  Celebes| S.e.  Of  Celebes| S.e.  Of  Celebes  Islands| S.o.  Celebes| S.of  Celebes| S.w.  Celebes| Se  Celebes| Se.  Celebes| South  Celebes| South  Of  Celebes| Sula- Celebes  Islands| Sulu  Islands. ( N.  Celebes)|Celebes  And  Flores  Islands| Indonesia:  Sulawesi| Indonesia| Ceram| Ceram  Islands| Ceram  Laut| Ceram  Laut  Islands| Cent.  D.  New  Guinea| Cent.  D.n.  Guinea| Cent.  Du.  New  Guinea| Cent.  Dut.  New  Guinea| Cent.  Dutch  N.  Guinea| Cent.  Dutch  New  Guinea| Centr.  Dutch  New  Guinea| D.   New  Guinea| D.  New  Guina| Du  New  Guinea| Du.  New  Guiana| Du.  New  Guinea ( East  Coast)| Dutch  New  Guin| Dutch  New  Guinea| Centr.  Molucca's| Centr.  Moluccas| Brit.  D.  New  Guinea| C.  D.  New  Guinea| C.d.  New  Guinea| Centr.du.  New  Guinea| Du.  New  Guinea ( East  Coast)| E.  C.  D.  New  Guinea| E.  Centr.  Du.  New  Guinea| E.centr.du.  New  Guinea| N.w.  D.  New  Guinea| N.w.du.  New  Guinea| North  Coast  D.  New  Guinea| S.  Of  D.  New  Guinea| S.c.  D.  New  Guinea| S.centr.  Du.  New  Guinea| S.centr.du  New  Guinea| S.centr.du.  New  Guinea| W.  Of  D.  New  Guinea| W.  Of  Du.  New  Guinea| Aru  Islands| Batavia| E.  Java| E.  Java  Islands| East  Of  Java| Java| Java  Islands| N.  Java| N.  Of  Java| N.  Of  Java  Islands| N.e.  Java| N.e.  Of  Java| S.  Java| S.  Java  Islands| S.  Of  Java| W.  Java| W.  Java  Islands| West  Java| Lombok| Lombok  Islands| N.  Lombok| N.  Lombok  Islands|Banda  Islands| Alor  Islands| Banggai| Batjan  Islands| Biak  Islands| N.  Du.  New  Guinea| N.  Of  D.  New  Guinea| N.  Of  Du.  New  Guinea| N.  W.   D.  New  Guinea| N.du.  New  Guinea| Timor| Timor  Islands| Timor  Laut| Timor  Laut  Islands. =  Tenimber| Timor  Laut  Islands. =  Tenimeber| Timor  Laut [ =  Tenimber  Islands.]| Timor- Leste| Toekang  Besi  Islands| Tomia  Islands| Buru| Buru  Islands| Banda  Islands|Banda  Islands'| Between  Celebes  And  Flores  Islands| Between  Celebes &  Flores  Islands| Between  Flores  And  Celebes| West  Borneo| D.  East  Indies| D.e.  Ind| D.e.  Indies| Dammer  Islands| Djampea  Islands| Engano  Islands| Lesser  Sunda  Islands", x, ignore.case = TRUE)) {
    return("Indonesia")
  } else {
    return(x)
  }
},
# Sri Lanka
  LKA <- function(x) {
  if (grepl(" Br.  India,  Ceylon| Central  Ceylon| Ceylon| Ceylon  Islands| N.  Ceylon| N.e.  Ceylon| N.w.  Ceylon| S.  Ceylon| S.e.  Coast  Of  Ceylon  Islands| South  Ceylon| W.  Ceylon| West  Ceylon| Sri  Lanka", x, ignore.case = TRUE)) {
    return("Sri Lanka")
  } else {
    return(x)
  }
},
# Japan
  JPN <- function(x) {
  if (grepl(" Central  Japan| E.  Of  Japan| Japan| Japan,| Japan,  Okinawa| Japan,  S.  Loo  Choo  Islands| N.  Japan| Off  Japan| S  Japan| S.  Japan| S.  Of  Japan| C.  Loo  Choo  Islands| Cent.  Loo  Choo  Islands| Cent.  Loo- Choo  Islands| Cent.  S.  Loo  Choo  Islands| Central  Loo  Choo  Islands| Central  N.  Loo  Choo  Islands| Japan,  S.  Loo  Choo  Islands| Loo  Choo  Islands| N  Loo  Choo  Islands| N.  Loo  Choo  Islands| N.  Loo  Chov  Islands| N.  Loo- Choo  Islands| N.  Loochoo  Islands| No.  S.  Loo  Choo  Islands| S.  Loo  Choo  Islands| S.  Loo- Choo  Islands| South  Loo  Choo  Islands| Ryukyu  Islands| So.  Ryukyus| Southern  Ryukyus| Bonin  Islands| Bonin  Isle", x, ignore.case = TRUE)) {
    return("Japan")
  } else {
    return(x)
  }
},
# Taiwan
  TWN <- function(x) {
  if (grepl(" Formosa,  Taiwan| Taiwan| C.  Formosa| Cent.  Formosa| Cent.  Formosa  Islands| Central  Formosa| Formosa  Islands| Formosa,  Taiwan| N  Formosa| N.  Formosa| S.  Formosa| S.w.  Formosa| South  Formosa", x, ignore.case = TRUE)) {
    return("Taiwan")
  } else {
    return(x)
  }
},
# Burma/Myanmar
  MMR <- function(x) {
  if (grepl(" Burma| Burma;  India| Burma;  Malaysia;  Thailand", x, ignore.case = TRUE)) {
    return("Burma")
  } else {
    return(x)
  }
},
# Cape verde
  CPV <- function(x) {
  if (grepl(" Cape  Verde| Cape  Verde  Islands", x, ignore.case = TRUE)) {
    return("Cape Verde")
  } else {
    return(x)
  }
},
# Costa Rica
  CRI <- function(x) {
  if (grepl(" Cocos  Island ( Costa  Rica)| Costa  Rica| Cocos  Island ( Costa  Rica)| Cocos  Islands", x, ignore.case = TRUE)) {
    return("Costa Rica")
  } else {
    return(x)
  }
},
# Brunei
  BRN <- function(x) {
  if (grepl(" Brunei| Brunei  Darussalam", x, ignore.case = TRUE)) {
    return("Nation of Brunei")
  } else {
    return(x)
  }
},
# Colombia
  COL <- function(x) {
  if (grepl(" Colombia| Columbia| Colòmbia", x, ignore.case = TRUE)) {
    return("Colombia")
  } else {
    return(x)
  }
},
# Somalia - Combining all of somalia including Somaliland and other colonical classification
  SOM <- function(x) {
  if (grepl(" Br.  Somaliland| Brit  Somaliland| Brit.  Somalailand| Brit.  Somaliland| British  Somaliland| Fr.  Somaliland| N.  Somaliland| N.e.  British  Somaliland| N.w.  Somaliland| North  Somaliland| S.  Somaliland| Somalia| Somaliland| W.  Somaliland| Western  Italian  Somaliland| British  Somililand", x, ignore.case = TRUE)) {
    return("Somalia")
  } else {
    return(x)
  }
},
#Norway
  NOR <- function(x) {
  if (grepl(" Centr.  Norway| N.  Norway| North  Norway| Norway| Norway;  Sweden;  Finland", x, ignore.case = TRUE)) {
    return("Norway")
  } else {
    return(x)
  }
},
# Vietnam
  VNM <- function(x) {
  if (grepl(" Cochin  China| Cochin- China| Vietnam| Annam| Annan| Tonkin", x, ignore.case = TRUE)) {
    return("Vietnam")
  } else {
    return(x)
  }
},
# Papua New Guinea
  PNG <- function(x) {
  if (grepl(" Br  New  Guinea| Br.  New  Guinea ( N.  Coast)| Brit.   New  Guinea| E.  Br.  New  Guinea| E.  Germ.  New  Guinea| East  Cent.  New  Guinea| Ger.  New  Guinea ( N.  Coast)| Ger.  New  Guinea,  N.  Coast| Germ.   New  Guinea| Germ.  D.  New  Guinea| Germ.  New  Guinea| German  Papua  New  Guinea| N.  Coast  Of  Ger.  New  Guinea| N.  Coast.  Of  Ger.  New  Guinea| N.  Germ.  New  Guinea| N.  Germ.  New  Guinea| N.br.  New  Guinea| N.e.  British  New  Guinea| N.e.br.  New  Guinea| N.w  New  Guinea| N.w.  Br.  New  Guinea| N.w.  Of   New  Guinea| N.w.  Of  New  Guinea| New  Guinea| Papua  New  Guinea| Papua,  New  Guinea| Rook  Islands. [ E.  Of  Ger.  New  Guinea]| S.e  New  Guinea| S.e.  Of   New  Guinea| S.e.  Of  Br.  New  Guinea| S.e.  Of  Brit.  New  Guinea| S.e.  Of  British  New  Guinea| S.e.  Of  New  Guinea| S.e.  Of  New  Guinea [ Louisiade  Archip.]| S.e.br.  New  Guinea| So.  Centr.  Du.  New  Guinea| South  East  Of  New  Guinea| W.  Of  New  Guinea| West  New  Guinea| Witu  Islands. [ N.e.  Of  New  Guinea]| Bismarck  Arch| Bismarck  Archip| Bismark  Arch| Bismark  Archip| Bismark  Islands|Admiralty|Admiralty  Group|Admiralty  Islands| Duke  Of  York  Islands| E.  Of  S.  New  Ireland| East  Of  New  Ireland| East  Of  S.  New  Ireland| East  Of  South  New  Ireland| New  Ireland| New  Ireland  Islands| S.e.  New  Ireland| S.e.  Of  New  Ireland| S.w.  New  Ireland| New  Britian  Islands| N.  Of  New  Hanover| New  Hanover| New  Hanover  Islands", x, ignore.case = TRUE)) {
    return("Papua New Guinea")
  } else {
    return(x)
  }
},
# New Zeland
  NZL <- function(x) {
  if (grepl(" Chatham  Islands;  New  Zealand| New  Zealand| The  Snares;  New  Zealand| Chatham  Islands| Tokelau| Antipodes  Island| Antipodes  Islands| Antipodes  Islands. [ S.e.  Of  New  Zealand]| Antipodes  Islands;  New  Zealand| Auckland  Island|Auckland  Island| Campbell  Island", x, ignore.case = TRUE)) {
    return("New Zealand")
  } else {
    return(x)
  }
},
# India
  IND <- function(x) {
  if (grepl(" India| S.  India| Andaman  And  Nicobar  Islands| Goa", x, ignore.case = TRUE)) {
    return("India")
  } else {
    return(x)
  }
},
# United Kingdom
  GBR <- function(x) {
  if (grepl(" England| United  Kingdom| Great  Britain| N.  Britain  Islands| N.  Of  New  Britain| Near  N.  New  Britain| New  Britain| New  Britain  Islands| Scotland| Wales| Northern  Ireland", x, ignore.case = TRUE)) {
    return("United Kingdom")
  } else {
    return(x)
  }
},
# Australia
  AUS <- function(x) {
  if (grepl(" Cocos ( Keeling)  Islands| Christmas  Island| Australia| S.w.  Australia| Gold  Coast| Gold  Coast  Hinter| Gold  Coast  Hinterland| Hinterland  Gold  Coast| Hinterland  Of  Gold  Coast", x, ignore.case = TRUE)) {
    return("Australia")
  } else {
    return(x)
  }
},
# Russia
  RUS <- function(x) {
  if (grepl(" Russia| Russian  Federation| N.  Russia| N  Russia| E.  Russia| E  Russia| S.  Russia| S.e.  Russia| So.  Russian  Altai| Commander  Islands| New  Siberia", x, ignore.case = TRUE)) {
    return("Russia")
  } else {
    return(x)
  }
},
# France
  FRA <- function(x) {
  if (grepl(" France| Territoire  Des  Terres  Australes  Et  Antarctiques  Françaises| França| Kerguelen  Islands;  France| N.  France| French  Guiana ( France)| N.  Coast  Of  France| N.w.  France| S.  France| S.e.  France| S.w.  France| French  Guiana| French  Southern  Territories| French  Guiana ( France)| Amsterdam  Island| Clipperton  Island| New  Caledonia", x, ignore.case = TRUE)) {
    return("France")
  } else {
    return(x)
  }
},
#Algeria
    DZA <- function(x) {
  if (grepl(" Algeria| N.  Algeria| S.  Algeria", x, ignore.case = TRUE)) {
    return("Algeria")
  } else {
    return(x)
  }
},
# Tonga
    TON <- function(x) {
  if (grepl(" Tonga| Alofa  Islands", x, ignore.case = TRUE)) {
    return("Tonga")
  } else {
    return(x)
  }
},
# French Polynesia
    PYF <- function(x) {
  if (grepl(" Austral  Islands| French  Polynesia", x, ignore.case = TRUE)) {
    return("French Polynesia")
  } else {
    return(x)
  }
},
# Venezuela
    VEN <- function(x) {
  if (grepl(" N.e.  Venezuela| Venezuela| Aves  Island", x, ignore.case = TRUE)) {
    return("Venezuela")
  } else {
    return(x)
  }
},
# China
    CHN <- function(x) {
  if (grepl(" C.  China| Centr.  China| China| E  China| E.  China| East  China| N.  China| N.e.  China| North  China| Off  S.  China| S.  China| S.  Of  China| S..  China| S.e  China| S.e.  China| S.w.  China| W  China| W.  China| Western  China", x, ignore.case = TRUE)) {
    return("China")
  } else {
    return(x)
  }
},
# Greece
    GRC <- function(x) {
  if (grepl(" Greece| Greeks| Cerigo  Islands| Crete| Crete  Islands", x, ignore.case = TRUE)) {
    return("Greece")
  } else {
    return(x)
  }
},
# Mauritius
    MUS <- function(x) {
  if (grepl(" Mauritius| Chagos  Archipelago", x, ignore.case = TRUE)) {
    return("Mauritius")
  } else {
    return(x)
  }
},
# Iceland
    ISL <- function(x) {
  if (grepl(" Coast  Of  N.  Iceland| Coast  Of  North  Iceland| Iceland| Iceland ( North)| N.  Iceland| N.e.  Iceland| No.  Iceland| North  Coast  Of  Iceland| North  Iceland", x, ignore.case = TRUE)) {
    return("Iceland")
  } else {
    return(x)
  }
},
# Comoros
    COM <- function(x) {
  if (grepl(" Comoro  Islands| Comoros", x, ignore.case = TRUE)) {
    return("Comoros")
  } else {
    return(x)
  }
},
# Ivory Coast
    CIV <- function(x) {
  if (grepl(" Cote  D'ivoire| Côte  D'ivoire| Ivory  Coast", x, ignore.case = TRUE)) {
    return("Ivory Coast")
  } else {
    return(x)
  }
},
# Ukraine
    UKR <- function(x) {
  if (grepl(" Ukraine| Crimea", x, ignore.case = TRUE)) {
    return("Ukraine")
  } else {
    return(x)
  }
}, 
# Libya
    LBY <- function(x) {
  if (grepl(" Libya| N.  Libya| Cyrenaica", x, ignore.case = TRUE)) {
    return("Libya")
  } else {
    return(x)
  }
},
# Poland
    POL <- function(x) {
  if (grepl(" N.  Of  Poland| Poland| Danzig  F.s", x, ignore.case = TRUE)) {
    return("Poland")
  } else {
    return(x)
  }
},
# DEMOCRATIC REPUBLIC OF THE CONGO
    COD <- function(x) {
  if (grepl(" Democratic  Republic  Congo| Democratic  Republic  Of  Congo| Democratic  Republic  Of  The  Congo", x, ignore.case = TRUE)) {
    return("Democratic  Republic  Of  The  Congo")
  } else {
    return(x)
  }
},
# Dominica
    DMA <- function(x) {
  if (grepl(" Dominica| W.  Indies,  Dominica  Islands", x, ignore.case = TRUE)) {
    return("Dominica")
  } else {
    return(x)
  }
},
# Dominican Republic
    DOM <- function(x) {
  if (grepl(" Dominican  Rep| Dominican  Republic", x, ignore.case = TRUE)) {
    return("Dominican Republic")
  } else {
    return(x)
  }
}, 
# Nigeria
    NGA <- function(x) {
  if (grepl(" N  Nigeria| N'ern  Nigeria| N.  Nigeria| Nigeria| No.  Nigeria| Northern  Nigeria| S  Nigeria| S'ern  Nigeria| S.  Nigera| S.  Nigeria| So  Nigeria| So.  Nigeria| South  Nigeria| Southern  Nigeria| W.  Nigeria", x, ignore.case = TRUE)) {
    return("Nigeria")
  } else {
    return(x)
  }
},
#  Vanuatu
    VUT <- function(x) {
  if (grepl(" Vanuatu| New  Hebrides  Islands| Southern  New  Hebrides", x, ignore.case = TRUE)) {
    return("Vanuatu")
  } else {
    return(x)
  }
},
# Solomon Islands
    SLB <- function(x) {
  if (grepl(" N.  Of  Solomon  Islands| S.  Solomon  Islands| Solomen  Islands| Solomon  Islands| Solomon  Islands:  New  Georgia  Group| Solomon's| Solomon's  Islands| Solomons| W.  Ofsolomon  Islands", x, ignore.case = TRUE)) {
    return("Solomon Islands")
  } else {
    return(x)
  }
},
# Chile
    CHL <- function(x) {
  if (grepl(" Easter  Island| Chile", x, ignore.case = TRUE)) {
    return("Chili")
  } else {
    return(x)
  }
},
# Faroe Islands
    FRO <- function(x) {
  if (grepl(" Faeroe  Islands| Faeroe  Islands;  Denmark| Faroe  Islands", x, ignore.case = TRUE)) {
    return("Faroe Islands")
  } else {
    return(x)
  }
},
# Micronesia
    FSM <- function(x) {
  if (grepl(" Federated  States  Of  Micronesia| Micronesia", x, ignore.case = TRUE)) {
    return("Micronesia")
  } else {
    return(x)
  }
}
)

for (i in seq_along(replace_functions)) {
  country_clean$country <- sapply(country_clean$country, replace_functions[[i]])
}
```


```{r, country count check after merge}
#to count whether unique entries reducing or not. 
country_counts_check <- country_clean %>%
  group_by(country) %>%
  summarise(count = n())
```


```{r warning=FALSE}
# coming back to this and trying again to see how things go this time

cleaned_df$StandardName <- countrycode(cleaned_df$country, origin = "country.name", destination = "iso3c")

#now let's get a sense of rows which didn't have any hits

non_matching_records <- cleaned_df %>% filter(is.na(StandardName))

#snippet to match back the ISO to country name - this needs to be done later as well, but for now keeping hit here and trying out

iso_codes <- unique(cleaned_df$StandardName) # ISO codes which has hits

country_names <- countrycode(iso_codes, origin = "iso3c", destination = "country.name") #original codes

#now lets create a data frame with standard name and code so that they can be merged with cleaned_df

iso_to_standard_mapping <- data.frame(
  ISOCode = iso_codes,
  StandardName = country_names
)

#now let's merge
cleaned_df <- merge(cleaned_df, iso_to_standard_mapping, by.x = "StandardName", by.y = "ISOCode", all.x = TRUE)

#for some reason column name is changing - let's rename it back as "country2"
colnames(cleaned_df)[colnames(cleaned_df) == "StandardName.y"] <- "country2"

```


